### ISSUE TITLE
allow formatting styles inside variable

### ISSUE THREAD

**Issue by ns096** [HamzaBenyazid/obsidian-live-variables#1]
I was looking into adding this myself but found your repository thanks!

I would love to be able to use the classic markdown syntax inside the property so I don't have to copy paste my string.
`example: "*fancy content*"`

Currently it is displayed as plain text. (Even when adding formatting ** to the outside of the variable.)
`<span id="example">*fancy content*</span> `
![image](https://github.com/user-attachments/assets/0326e77e-3630-4903-acf5-ec3bf92252f6)
![image](https://github.com/user-attachments/assets/6fdab3a0-8b81-4167-90d3-b4bbae554193)

**It should look like this in my case**
![image](https://github.com/user-attachments/assets/6608b401-2625-4f44-ba22-1f7ed8d63105)

**Comment by HamzaBenyazid** [comment]
Thank you @ns096, glad that you find this useful. 

Great suggestion, I would love to have this feature too. 

The only way that I can think of to develop this, is by converting the markdown syntax in the property into html and then insert it to the content. The downside of this, is that it will create some boilerplate html syntax, like `example: "*fancy content*"` will be inserted as `<span id="example"><em>fancy content</em></span>`, however, this wont be a big deal if you only care about the rendered content. 

This feature must be optional as not all users would like to treat properties as markdown, users might want to use `*fancy content*` as it is.

Thanks for the great suggestion, I will start working on it soon.
