### ISSUE TITLE
Variables not immediately updating

### ISSUE THREAD

**Issue by LiamSwayne** [HamzaBenyazid/obsidian-live-variables#16]
When I update a variable in the front-matter in source mode it doesn't instantly update the variable instances, and only updates once I close and re-open the tab.

**Comment by HamzaBenyazid** [comment]
Does it not update them in the current active tab, or in other tabs ?

**Comment by LiamSwayne** [comment]
In the current active tab. Example:

https://github.com/user-attachments/assets/219bc66f-d151-40c6-a986-8e4540306ca6

**Comment by HamzaBenyazid** [comment]
This is weird, it's working for me.


https://github.com/user-attachments/assets/63f1726c-78ad-471b-948b-a9ede00bd2ec

**Comment by HamzaBenyazid** [comment]
Can you send me a screenshot of any error shown in the console when you change the value

**Comment by LiamSwayne** [comment]
I didn't get an error

**Comment by HamzaBenyazid** [comment]
I cannot reproduce the issue, can you try using it in an empty vault, where no other plugin is installed, just to make sure there isn't any interference from other plugins
