### ISSUE TITLE
Vault wide or hierarchical setting and use of variables

### ISSUE THREAD

**Issue by woerndl** [HamzaBenyazid/obsidian-live-variables#4]
Hey Hamza,

great plugin. I was just looking for this and you created it just 3 months ago, perfect timing.

I have a feature suggestion: What do you think about pulling the variable values not just from the current note, but vault wide or better yet hierarchical. Higher level variables could get overriden down to the current note. But for my use case vault wide would also do. What do you think?

**Comment by HamzaBenyazid** [comment]
Hi Alexander,

I'm glad you found this helpful! Your suggestion is excellent—having global environment variables would be incredibly useful. While fetching variables from the parent or across the vault is straightforward, updating all occurrences across multiple files when a variable is changed could be a bit more challenging. Iterating through every file could lead to performance issues, so implementing some form of indexed variable tracking will likely be necessary.

Thanks again for the suggestion! I’m excited about the challenge and will start working on it soon.

**Comment by woerndl** [comment]
Maybe it would be enough to update the occurrences when the note is opened (at least for starters). There are probably edge cases where it still leads to separate challenges that would need to be adressed (parts of note with variable included in another note or similiar), but this way it should at least not lead to performance issues, which is a very valid reason not to loop through notes.

**Comment by HamzaBenyazid** [comment]
You're right, updating occurences on file opening is a good way to start. It should be easy to implement. The inserted variable will have some hidden info like variable id and the path where the variable is defined. So rendering it when the file is opened should be straightforward.
Also, on variable change, we can trigger the update for occurences inside the same file(where the variable is defined), this way the user wouldn't need to re-open the file.
This approach will guarentee that the user will always see the updated value.

**Comment by HamzaBenyazid** [comment]
Regarding [tag-wrangler](https://github.com/pjeby/tag-wrangler?tab=readme-ov-file#renaming-tags), I'll check how they handled this issue and see if it works in this case
