### ISSUE TITLE
Suggestion : support for nested properties

### ISSUE THREAD

**Issue by GuanFuling** [HamzaBenyazid/obsidian-live-variables#6]
Hi !
I think it's a good idea ! Unfortunately, i mainly use nested properties, and it seemed it did not work with that. Do you think it will be one of your futur features ?
Anyway thanks for this plugin, it's very good !

**Comment by HamzaBenyazid** [comment]
Hi, thanks for support.
This seem like a good feature, I was not aware of nested properties, but that I checked, I find it very useful and it should be supported.
